
const defaultMovies=[{id:'m1',title:'Eagle Adventure',rating:'PG-13',duration:'2h 02m',price:12,desc:'An action movie about a team racing to stop a major threat.',times:['1:30 PM','4:15 PM','7:00 PM']},{id:'m2',title:'Campus Nights',rating:'PG',duration:'1h 45m',price:10,desc:'A comedy about friends planning one unforgettable weekend.',times:['12:00 PM','3:00 PM','8:30 PM']},{id:'m3',title:'The Last Orbit',rating:'PG-13',duration:'2h 18m',price:14,desc:'A sci-fi story about a mission that changes the future of space travel.',times:['2:20 PM','5:40 PM','9:10 PM']}];
function init(){if(!localStorage.getItem('movies')) localStorage.setItem('movies',JSON.stringify(defaultMovies));if(!localStorage.getItem('bookings')) localStorage.setItem('bookings',JSON.stringify([{movie:'Eagle Adventure',showtime:'7:00 PM',seats:['B3','B4'],total:24,customer:'Sample Customer'}]));}
function movies(){init();return JSON.parse(localStorage.getItem('movies'))} function bookings(){init();return JSON.parse(localStorage.getItem('bookings'))} function saveMovies(m){localStorage.setItem('movies',JSON.stringify(m))} function saveBookings(b){localStorage.setItem('bookings',JSON.stringify(b))} function qs(n){return new URLSearchParams(location.search).get(n)} function setBooking(obj){localStorage.setItem('currentBooking',JSON.stringify({...getBooking(),...obj}))} function getBooking(){return JSON.parse(localStorage.getItem('currentBooking')||'{}')}
function login(){const u=document.getElementById('user').value.trim();const p=document.getElementById('pass').value.trim();if(u==='customer'&&p==='customer123'){localStorage.setItem('role','customer');location.href='index.html'}else if(u==='manager'&&p==='manager123'){localStorage.setItem('role','manager');location.href='manager.html'}else{document.getElementById('msg').textContent='Invalid login. Try customer/customer123 or manager/manager123.'}}
function renderHome(){const el=document.getElementById('movies');if(!el)return;el.innerHTML=movies().map(m=>`<div class="card movie-card"><div><div class="poster">🎬</div><h2>${m.title}</h2><p>${m.rating} • ${m.duration}</p><p>${m.desc}</p></div><a class="btn" href="details.html?id=${m.id}">View Details</a></div>`).join('')}
function renderDetails(){const id=qs('id')||'m1';const m=movies().find(x=>x.id===id);if(!m)return;document.getElementById('title').textContent=m.title;document.getElementById('desc').textContent=m.desc;document.getElementById('meta').textContent=`${m.rating} • ${m.duration} • $${m.price} per ticket`;document.getElementById('times').innerHTML=m.times.map(t=>`<button class="showtime" onclick="setBooking({movieId:'${m.id}',movie:'${m.title}',price:${m.price},showtime:'${t}'});location.href='seats.html'">${t}</button>`).join('')}
function renderSeats(){const grid=document.getElementById('seatgrid');if(!grid)return;const taken=['A1','A2','C3','D4','E5'];let seats=[];['A','B','C','D','E'].forEach(r=>{for(let i=1;i<=6;i++)seats.push(r+i)});grid.innerHTML=seats.map(s=>`<button class="seat ${taken.includes(s)?'taken':''}" ${taken.includes(s)?'disabled':''} onclick="this.classList.toggle('selected')">${s}</button>`).join('')}
function continueCheckout(){const selected=[...document.querySelectorAll('.seat.selected')].map(x=>x.textContent);if(selected.length===0){alert('Please select at least one seat.');return}const b=getBooking();setBooking({seats:selected,total:selected.length*(b.price||12)});location.href='checkout.html'}
function renderCheckout(){const b=getBooking();const el=document.getElementById('summary');if(!el)return;el.innerHTML=`<strong>Movie:</strong> ${b.movie||'N/A'}<br><strong>Showtime:</strong> ${b.showtime||'N/A'}<br><strong>Seats:</strong> ${(b.seats||[]).join(', ')}<br><strong>Total:</strong> $${b.total||0}`}
function confirmPurchase(){const name=document.getElementById('name').value.trim();const email=document.getElementById('email').value.trim();if(!name||!email){alert('Please enter name and email.');return}const b={...getBooking(),customer:name,email,confirmation:'MT'+Math.floor(Math.random()*90000+10000)};const list=bookings();list.push(b);saveBookings(list);localStorage.setItem('lastBooking',JSON.stringify(b));location.href='confirmation.html'}
function renderConfirmation(){const b=JSON.parse(localStorage.getItem('lastBooking')||'{}');const el=document.getElementById('confirm');if(!el)return;el.innerHTML=`<h2>Booking Confirmed</h2><p><strong>Confirmation #:</strong> ${b.confirmation||'MT00000'}</p><p><strong>Movie:</strong> ${b.movie||''}</p><p><strong>Showtime:</strong> ${b.showtime||''}</p><p><strong>Seats:</strong> ${(b.seats||[]).join(', ')}</p><p><strong>Total:</strong> $${b.total||0}</p>`}
function renderManage(){const el=document.getElementById('movieTable');if(!el)return;el.innerHTML=movies().map(m=>`<tr><td>${m.title}</td><td>${m.rating}</td><td>${m.duration}</td><td>$${m.price}</td><td><button class="btn secondary" onclick="deleteMovie('${m.id}')">Delete</button></td></tr>`).join('')}
function addMovie(){let m=movies();m.push({id:'m'+Date.now(),title:document.getElementById('mtitle').value||'New Movie',rating:document.getElementById('rating').value||'PG',duration:document.getElementById('duration').value||'1h 50m',price:Number(document.getElementById('price').value)||12,desc:'New movie added by manager.',times:['1:00 PM','6:00 PM']});saveMovies(m);renderManage()}
function deleteMovie(id){saveMovies(movies().filter(m=>m.id!==id));renderManage()}
function renderReports(){const b=bookings();const revenue=b.reduce((s,x)=>s+Number(x.total||0),0);document.getElementById('totalBookings').textContent=b.length;document.getElementById('revenue').textContent='$'+revenue;document.getElementById('avg').textContent='$'+(b.length?Math.round(revenue/b.length):0);document.getElementById('rows').innerHTML=b.map(x=>`<tr><td>${x.customer||'Guest'}</td><td>${x.movie}</td><td>${x.showtime}</td><td>${(x.seats||[]).join(', ')}</td><td>$${x.total}</td></tr>`).join('')}
document.addEventListener('DOMContentLoaded',()=>{init();renderHome();renderDetails();renderSeats();renderCheckout();renderConfirmation();renderManage();renderReports();});
